package org.mule.demo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-02-06T14:21:36.421-08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://example.mule.mulesoft.com/", name = "contact")
@XmlSeeAlso({ObjectFactory.class})
public interface Contact {

    @WebMethod
    @RequestWrapper(localName = "contact", targetNamespace = "http://example.mule.mulesoft.com/", className = "org.mule.demo.soap.Contact_Type")
    @ResponseWrapper(localName = "contactResponse", targetNamespace = "http://example.mule.mulesoft.com/", className = "org.mule.demo.soap.ContactResponse")
    @WebResult(name = "ID", targetNamespace = "")
    public java.lang.String contact(
        @WebParam(name = "FName", targetNamespace = "")
        java.lang.String fName,
        @WebParam(name = "Lname", targetNamespace = "")
        java.lang.String lname,
        @WebParam(name = "SSN", targetNamespace = "")
        java.lang.String ssn
    );
}
