
package org.mule.demo.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-02-06T14:21:36.360-08:00
 * Generated source version: 2.5.1
 * 
 */
public final class Contact_ContactPort_Client {

    private static final QName SERVICE_NAME = new QName("http://example.mule.mulesoft.com/", "contactService");

    private Contact_ContactPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ContactService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ContactService ss = new ContactService(wsdlURL, SERVICE_NAME);
        Contact port = ss.getContactPort();  
        
        {
        System.out.println("Invoking contact...");
        java.lang.String _contact_fName = "";
        java.lang.String _contact_lname = "";
        java.lang.String _contact_ssn = "";
        java.lang.String _contact__return = port.contact(_contact_fName, _contact_lname, _contact_ssn);
        System.out.println("contact.result=" + _contact__return);


        }

        System.exit(0);
    }

}
